name: Run nimble test

on: push

jobs:
  nimble-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nim: [ '1.4.0', 'stable', 'devel' ]
    name: Nimble test with nim version ${{ matrix.nim }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - run: nimble test