name: Run nimble test

on: push

jobs:
  nimble-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        nim:
          - '1.4.0'
          - 'stable'
          - 'devel'
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macOS-latest'

    name: nimble test ${{ matrix.nim }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - run: nimble test